export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCEED = "USER_LOGIN_SUCCEED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED";
export const USER_LOGOUT_SUCCEED = "USER_LOGOUT_SUCCEED";

export const USER_FORGOT_PASSWORD_REQUEST = "USER_FORGOT_PASSWORD_REQUEST";
export const USER_FORGOT_PASSWORD_FAILED = "USER_FORGOT_PASSWORD_FAILED";
export const USER_FORGOT_PASSWORD_SUCCEED = "USER_FORGOT_PASSWORD_SUCCEED";

export const USER_ADD_REQUEST = "USER_ADD_REQUEST";
export const USER_ADD_FAILED = "USER_ADD_FAILED";
export const USER_ADD_SUCCEED = "USER_ADD_SUCCEED";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED";
export const USER_UPDATE_SUCCEED = "USER_UPDATE_SUCCEED";

export const USER_DETAILS_GETTING_REQUEST= 'USER_DETAILS_REQUEST';
export const USER_DETAILS_GETTING_SUCCEED= 'USER_DETAILS_SUCCEED';
export const USER_DETAILS_GETTING_FAILED= 'USER_DETAILS_FAILED';

export const USER_DELETE_REQUEST='USER_DELETE_REQUEST';
export const USER_DELETE_SUCCEED='USER_DELETE_SUCCEED';
export const USER_DELETE_FAILED='USER_DELETE_FAILED';

export const USER_SEARCH_REQUEST='USER_SEARCH_REQUEST';
export const USER_SEARCH_SUCCEED='USER_SEARCH_SUCCEED';
export const USER_SEARCH_FAILED='USER_SEARCH_FAILED';

